/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiBuilderRouteImport } from './routes/api/builder'
import { Route as ApiBypassRouteImport } from './routes/api/bypass'
import { Route as ApiCaptionsRouteImport } from './routes/api/captions'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiRelayRouteImport } from './routes/api/relay'
import { Route as ApiUnlockRouteImport } from './routes/api/unlock'
import { Route as ApiYtdlpRouteImport } from './routes/api/ytdlp'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderRoute = ApiBuilderRouteImport.update({
  id: '/api/builder',
  path: '/api/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBypassRoute = ApiBypassRouteImport.update({
  id: '/api/bypass',
  path: '/api/bypass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptionsRoute = ApiCaptionsRouteImport.update({
  id: '/api/captions',
  path: '/api/captions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelayRoute = ApiRelayRouteImport.update({
  id: '/api/relay',
  path: '/api/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlockRoute = ApiUnlockRouteImport.update({
  id: '/api/unlock',
  path: '/api/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYtdlpRoute = ApiYtdlpRouteImport.update({
  id: '/api/ytdlp',
  path: '/api/ytdlp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/bypass': typeof ApiBypassRoute
  '/api/captions': typeof ApiCaptionsRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/relay': typeof ApiRelayRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/ytdlp': typeof ApiYtdlpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/bypass': typeof ApiBypassRoute
  '/api/captions': typeof ApiCaptionsRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/relay': typeof ApiRelayRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/ytdlp': typeof ApiYtdlpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/bypass': typeof ApiBypassRoute
  '/api/captions': typeof ApiCaptionsRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/relay': typeof ApiRelayRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/ytdlp': typeof ApiYtdlpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/builder'
    | '/api/bypass'
    | '/api/captions'
    | '/api/download'
    | '/api/feed'
    | '/api/health'
    | '/api/relay'
    | '/api/unlock'
    | '/api/ytdlp'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/builder'
    | '/api/bypass'
    | '/api/captions'
    | '/api/download'
    | '/api/feed'
    | '/api/health'
    | '/api/relay'
    | '/api/unlock'
    | '/api/ytdlp'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/builder'
    | '/api/bypass'
    | '/api/captions'
    | '/api/download'
    | '/api/feed'
    | '/api/health'
    | '/api/relay'
    | '/api/unlock'
    | '/api/ytdlp'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiBuilderRoute: typeof ApiBuilderRoute
  ApiBypassRoute: typeof ApiBypassRoute
  ApiCaptionsRoute: typeof ApiCaptionsRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRelayRoute: typeof ApiRelayRoute
  ApiUnlockRoute: typeof ApiUnlockRoute
  ApiYtdlpRoute: typeof ApiYtdlpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder': {
      id: '/api/builder'
      path: '/api/builder'
      fullPath: '/api/builder'
      preLoaderRoute: typeof ApiBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bypass': {
      id: '/api/bypass'
      path: '/api/bypass'
      fullPath: '/api/bypass'
      preLoaderRoute: typeof ApiBypassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/captions': {
      id: '/api/captions'
      path: '/api/captions'
      fullPath: '/api/captions'
      preLoaderRoute: typeof ApiCaptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relay': {
      id: '/api/relay'
      path: '/api/relay'
      fullPath: '/api/relay'
      preLoaderRoute: typeof ApiRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlock': {
      id: '/api/unlock'
      path: '/api/unlock'
      fullPath: '/api/unlock'
      preLoaderRoute: typeof ApiUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ytdlp': {
      id: '/api/ytdlp'
      path: '/api/ytdlp'
      fullPath: '/api/ytdlp'
      preLoaderRoute: typeof ApiYtdlpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiBuilderRoute: ApiBuilderRoute,
  ApiBypassRoute: ApiBypassRoute,
  ApiCaptionsRoute: ApiCaptionsRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRelayRoute: ApiRelayRoute,
  ApiUnlockRoute: ApiUnlockRoute,
  ApiYtdlpRoute: ApiYtdlpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
